name: test_built_value
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_value: ^8.1.1

dev_dependencies:
  build_runner: ^2.0.6
  built_value_generator: ^8.1.1
  pedantic: ^1.10.0
  test: ^1.16.0
