name: test_built_value
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/hoc081098/test_built_value

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  built_value: ^8.4.0

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.2.0
  built_value_generator: ^8.4.0
  test: ^1.21.4
